export const LANG_EN = {
  company: 'Clarkson Eyecare',
  title: 'Scheduling Application',
  search_radius: 'Search Radius',
  in_my_state: 'Are you in my state?',
  results_within: 'Results within',
  title_find_us: 'Find a location near you.',
  title_login: 'Log in to your account',
  title_profile: 'Tell us a bit about yourself',
  title_schedule: 'Select a day and time below.',
  title_confirm: 'Review your appointment info below and submit.',
  title_thanks: "Thanks, we'll see you soon!",
  have_account: 'Already have an account?',
  next_steps: 'Next Steps',
  login_here: 'Login here',
  step_one_title: 'Step 1 of 4',
  step_two_title: 'Step 2 of 4',
  step_three_title: 'Step 3 of 4',
  step_four_title: 'Step 4 of 4',
  step_five_title: 'Cofirmation',
  map_view: 'Map View',
  directions: 'Directions',
  schedule_appointment: 'Schedule an Appointment',
  label_appointment_for: 'Appointment for',
  label_location: 'Location',
  label_date_and_time: 'Date and Time',
  arrival_info: 'When you plan your arrival time, please note our LateArrival Policy. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  save_time_title: 'Want to save yourself some time?',
  save_time_text: 'Complete your patient info sheet before you arrive.',
  create_account_title: 'Create an Account?',
  create_account_text: 'Create an account to manage your appointments faster.',
  why_us_title: 'Why Clarkson?',
  why_us_text: 'The real question is, why not?',
  forms: {
    city_state_zip: 'City, State, or Zip Code',
    legend_contact_info: 'Contact Info',
    first_name: 'First Name',
    last_name: 'Last Name',
    phone_number: 'First Name',
    email_address: 'Email Address',
    date_of_birth: 'Date of Birth (DD-MM-YYYY)',
    legend_use_insurance: 'Will you be using insurance?',
    policy_holder: 'Name of Policy Holder',
    insurance_provider: 'Insurance Provider',
    group_number: 'Group Number',
    policy_number: 'Policy Number',
    password: 'Password',
    acknowledge: 'By checking this, I acknowledge that I did not read this content which needs to be changed.',
    legend_select_time: 'Select Available Time:',
    buttons: {
      clear: 'Clear',
      apply_filters: 'Apply Filters',
      continue: 'Continue',
      yes: 'Yes',
      no: 'No',
      login: 'Log In',
      change: 'Change',
      schedule: 'Schedule My Appointment',
      complete_form: 'Complete Form',
      create_account: 'Create an Account',
      learn_more: 'Learn More'
    }
  }
}